steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:$COMMIT_SHA', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ocr-deployed'
  - '--image'
  - 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:$COMMIT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'MONGODB_URI=${_MONGODB_URI},MISTRAL_API_KEY=${_MISTRAL_API_KEY}'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--port'
  - '8080'

# Tag the image with 'latest' for easier reference
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:$COMMIT_SHA', 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:latest']

# Push the 'latest' tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:latest']

images:
- 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:$COMMIT_SHA'
- 'asia-south1-docker.pkg.dev/shiv-automation/ocr-extraction/ocr-deployed:latest'

timeout: '1800s'  # 30 minutes timeout

# Define available substitutions
substitutions:
  _MONGODB_URI: ''  # This will be set in the Cloud Build trigger
  _MISTRAL_API_KEY: ''  # This will be set in the Cloud Build trigger
  _REGION: 'asia-south1'  # Mumbai region
  _REPOSITORY: 'ocr-deployed'  # Your Artifact Registry repository name

# Define available options
options:
  logging: CLOUD_LOGGING_ONLY 